### ISSUE TITLE
What I had to change for this to work

### ISSUE THREAD

**Issue by johannesE** [bradymholt/ansible-rails#3]
First of all let me thank you for this awesome repository.

I thought I'd make an issue with all the small things that I had to change that were not in the readme for this to work. Then you can decide for yourself if it's useful for everyone or not.

- Manually install `python-simplejson` on the host (that is normal for ansible)
- The readme does not mention the group_vars/all file. But there is still an app name (`hfbctheoaks`) in there.
- In `provision.yml` I had to change the roles to the following:
```roles:
    - s3cmd
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_user: 'root'
      }
    - nginx-passenger
    - mysql
    - webserver
```
The error was: fatal: [X.X.X.X]: FAILED! => {"failed": true, "msg": "Failed to change ownership of the temporary files Ansible needs to create despite connecting as root.  Unprivileged become user would be unable to read the file."}
- Remove the line `passenger_enabled on;` from `etc_nginx_sites-available.conf.j2` and manually uncomment `# include /etc/nginx/passenger.conf;` from `/etc/nginx/nginx.conf`
- remove
```- name: Ensure passenger_root is set
  lineinfile:
    dest=/etc/nginx/nginx.conf
    state=present
    backup=yes
    regexp='#?\s*passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;'
    line='passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;'

- name: Ensure passenger_ruby is set
  lineinfile:
    dest=/etc/nginx/nginx.conf
    state=present
    backup=yes
    backrefs=yes
    regexp='#?\s*passenger_ruby /usr/bin/passenger_free_ruby;'
    line='passenger_ruby /usr/bin/passenger_free_ruby;'
```
- remove `groups=rvm` from the task `add user and create ssh key` (group didn't exist). I hope it still deploys properly.. 

Btw: I used root as the deploy_user, which was probably a very bad idea because rvm is messing with me now.

**Comment by bradymholt** [comment]
Thanks for the writeup!  I appreciate this.  Would you be up for submitting a PR to update the README to incorporate these things?

**Comment by johannesE** [comment]
No, I'm sorry, but I have given up. I'm using the one-click installer now. This looked amazing in the beginning, but in the end I don't have the time to get it to work.

**Comment by bradymholt** [comment]
I hadn't touched this repo in awhile but I just merged https://github.com/bradymholt/ansible-rails/pull/4 which makes some major updates.  I've tested on a Digital Ocean Ubuntu 16 server with Rails 5.

**Comment by johannesE** [comment]
That looks promising. I actually need to migrate a rails 4 app with spree to a vps, but I'm gonna take another look at this and get back to you.

**Comment by johannesE** [comment]
Wow, I'm seriously impressed. It ran through without an issue on the first try and even deployed my app. You made my day. Thank you!

If you ever need some elixir advice, want to chat, or there is a way to remotely pay for a big cup of coffee, just let me know.
