### ISSUE TITLE
rvm1_user has to be root

### ISSUE THREAD

**Issue by looneym** [bradymholt/ansible-rails#5]
Hello 👋 

First off thanks for the awesome write up and code. 

I ran into some issues running this playbook however, specifically the rvm install role. I eventually got it to work by modifying `roles/rvm_io.ruby/defaults/main.yml` so that `rvm1_user` was root. 

I did some digging and found that on (what appears to be) the source repo for the RVM playbook, this user was already set to root: https://github.com/snowplow/ansible-playbooks/blob/master/roles/rvm_io.rvm1-ruby/defaults/main.yml#L19

I notice the closed issue here https://github.com/bradymholt/ansible-rails/issues/3 which makes mention of running the role like this:

```
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_user: 'root'
      }
```

But it's closed as having been addressed by your rails 5 upgrades. 

I'm running this via packer and have made a few modifications in general so have definitely introduced some disparity between your source code and mine but I was wondering if there's a particular reason that you are doing something different with this user var? I did a blame on the linked repo and it hasn't been modified recently.

**Comment by bradymholt** [comment]
Honestly, I don't remember the specifics offhand but I do believe I encountered a problem with rvm installation when it was installed as root.  And, I think rvm recommends against installing as root in general.  If you are hitting this with the latest `master` branch here, I'd welcome a PR if I am doing something wrong.  But, it sounds like your mods for packer might be playing into what you are seeing.

**Comment by looneym** [comment]
Yep that's reasonable. Thanks for the reply.
